#Plasmo Voice Changer preset
#Mon Jul 20 22:13:27 MSK 2026
autotuneKey=0
autotuneMix=0.0
autotuneScale=0
autotuneStrength=0.6
bitDepth=16.0
distortion=0.0
echoDelayMs=90
echoFeedback=0.08
echoMix=0.04
enabled=false
formant=0.92
gain=1.08
highEq=-1.2
lowEq=2.2
midEq=0.0
mix=0.8
noise=0.0
pitch=0.92
preset=MAN
robotFrequency=40
robotMix=0.0
savedPresetName=
selfListen=false
strength=100
tremoloDepth=0.0
tremoloRate=2.2
